version: "3"
services:
  app:
    container_name: webpushsender-app
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - default
      - luklac
  redis:
    image: redis:7.0.7-alpine
    container_name: webpushsender-redis
    restart: unless-stopped
    networks:
      - default
networks:
  luklac:
    external: true